name: Lint Files

on:
  push:
    branches: [ main, main-nuxt ]
  pull_request:
    branches: [ main, main-nuxt ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install Dependencies
        run: yarn

      - name: Run Code Lint report
        run: yarn lint:report

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: eslint_report.json

      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report.json
          path: eslint_report.json
