
name: reviewdog
on:
  pull_request:
    branches: [ main-nuxt ]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: eslint --quiet --ignore-path .gitignore --ext .js,.ts,.vue . -f rdjson . | reviewdog -f=rdjson -reporter=github-pr-review -filter-mode=nofilter -fail-on-error

      # - name: Run eslint with reviewdog
      #   uses: reviewdog/action-eslint@v1.14.0
      #   with:
      #     level: error
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     reporter: github-pr-review
      #     eslint_flags: "--quiet --ignore-path .gitignore --ext .js,.ts,.vue ."
      #     fail_on_error: true
      #     filter_mode: nofilter
